FY21Q2 content refresh
microsoftgraph/msgraph-training-aspnetmvcapp pull request #61
Opened 2020-12-12 21:36 UTC by andrewconnell

- run through all exercise steps in associated MSLearn module to validate good working order
- updated steps & fixed typos where necessary
- updated slides where necessary
- update code samples to reflect MSLearn HOL exercise refresh & updates

2021-01-05 21:09 UTC, jasonjoh requested changes

2021-01-05 21:09 UTC, jasonjoh commented on Demos/01-create-app/graph-tutorial/Controllers/HomeController.cs
> +﻿using System;
A number of files here dropped the copyright notice.

2021-01-05 21:09 UTC, jasonjoh commented on Demos/01-create-app/graph-tutorial/Startup.cs
> +﻿using Microsoft.Owin;
Copyright

2021-01-05 21:09 UTC, jasonjoh commented on Demos/02-add-aad-auth/graph-tutorial/Controllers/HomeController.cs
> +﻿using System;
Copyright

2021-01-05 21:09 UTC, jasonjoh commented on Demos/03-add-msgraph/graph-tutorial/Controllers/HomeController.cs
> +﻿using System;
Copyright

2021-01-14 15:48 UTC, andrewconnell commented
Sorry about the copyright issue... slipped my edits. Fixed in latest commit.

2021-01-14 19:38 UTC, jasonjoh approved these changes

2021-01-14 19:38 UTC, merged

2021-01-14 19:38 UTC, jasonjoh commented
Thanks!